play_motion:
  motions:
    extend:
      joints:
      - torso_lift_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      points:
      - positions: [0.15, 0.53, 0.74, 1.99, 1.51, 0.46, 0.84, -1.09, 0.53, 0.74, 1.99, 1.51, 0.46, 0.84, -1.09]
        time_from_start: 5.0
      meta:
        name: "Extend"
        usage: telepresence
        description: "Extend both arms"

    extend_left:
      joints:
      - torso_lift_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      points:
      - positions: [0.15, 0.53, 0.74, 1.99, 1.51, 0.46, 0.84, -1.09]
        time_from_start: 5.0
      meta:
        name: "Extend left"
        usage: telepresence
        description: "Extend left arm"

    extend_right:
      joints:
      - torso_lift_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      points:
      - positions: [0.15, 0.53, 0.74, 1.99, 1.51, 0.46, 0.84, -1.09]
        time_from_start: 5.0
      meta:
        name: "Extend right"
        usage: telepresence
        description: "Extend right arm"
