play_motion:
  controllers: [arm_controller, torso_controller]

  motions:
    home:
      joints: [torso_lift_joint, arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
      points:
      - positions: [0.25, 0.20, 0.35, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 0.5
      - positions: [0.18, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 4.0
      - positions: [0.15, 0.20, -1.34, -0.20, 1.94, -1.57, 1.37, 0.0]
        time_from_start: 7.0
      meta:
        name: Home
        usage: demo
        description: 'Go home'

    extend:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint, torso_lift_joint]
      points:
      - positions: [1.57, -1.0, -3.14, 1.0, -1.57, 0.0, 0.0, 0.15]
        time_from_start: 5.0
      meta:
        name: Extend
        usage: demo
        description: 'Extend arm'
